import type { Metadata } from 'next';
import './globals.css';
import { UserProvider } from '@/components/context/userContext';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'E-Signify',
  description: 'E-Signify Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <UserProvider>
          <Toaster position="top-center" />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
